import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Script from "next/script";

import GlobalProvider from "./provider";
import LayoutMain from "./main";
import Navbar from "@/components/navbar";
import NavbarOverlay from "@/components/navbar/overlay";
import "./globals.css";
import Footer from "@/components/footer";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <body
        className={`${inter.className} h-full w-screen max-w-full [--gutter-size:theme(spacing.5)] sm:[--container-size:calc(theme(maxWidth.xl)-theme(spacing.6))] sm:[--gutter-size:calc((100vw-(theme(maxWidth.xl)-theme(spacing.6)))/2)] md:[--container-size:calc(theme(maxWidth.3xl)-theme(spacing.6))] md:[--gutter-size:calc((100vw-(theme(maxWidth.3xl)-theme(spacing.6)))/2)] lg:[--container-size:calc(theme(maxWidth.5xl)-theme(spacing.8))] lg:[--gutter-size:calc((100vw-(theme(maxWidth.5xl)-theme(spacing.8)))/2)] xl:[--container-size:calc(theme(maxWidth.6xl)-theme(spacing.8))] xl:[--gutter-size:calc((100vw-(theme(maxWidth.6xl)-theme(spacing.8)))/2)]`}
      >
        <GlobalProvider>
          <Navbar />
          <NavbarOverlay />
          <div className="pointer-events-none fixed left-0 top-0 z-[103] h-screen w-full max-w-full overflow-auto opacity-0 transition-opacity duration-700" />

          <LayoutMain>{children}</LayoutMain>

          <Footer />
        </GlobalProvider>
        <Toaster />
      </body>
      <Script id="">0</Script>
    </html>
  );
};

export default RootLayout;
