import React from "react";
import fs from "fs";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import GlobalProvider from "./provider";
import LayoutMain from "./main";
import Navbar from "@/components/navbar";
import NavbarOverlay from "@/components/navbar/overlay";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalProvider>
          <Navbar />
          <NavbarOverlay />
          <div className="pointer-events-none fixed left-0 top-0 z-[103] h-screen w-screen overflow-auto opacity-0 transition-opacity duration-700" />

          <LayoutMain>{children}</LayoutMain>
        </GlobalProvider>
      </body>
    </html>
  );
};

export default RootLayout;
